name: Convert to ipynb
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        sudo apt-get install python3-venv
        python3 -m venv env
        source env/bin/activate
        pip3 install --upgrade pip setuptools wheel
        pip3 install -r requirements.txt
    - name: convert to ipynb
      run: |
        source env/bin/activate
        jupytext --to notebook --execute flare_sketch.Rmd
    - name: Upload ipynb version
      uses: actions/upload-artifact@v2
      with:
        name: Notebook in ipynb format
        path: |
          flare_sketch.ipynb
          *.py
